services:
  app:
    build: .
    container_name: house_of_jordan_api
    restart: unless-stopped
    ports:
      - "5193:8080"
    volumes:
      - ./HouseOfJordan.Api/houseofjordan.db:/app/houseofjordan.db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
